### ISSUE TITLE
Jet Pineappl grids

### ISSUE THREAD

**Issue by t7phy** [NNPDF/theories#5]
Hi @scarlehoff 

I have a few jet theory grids that should be added to theories repo, however there are two new aspects to them:
1. they are at NNLO
2. they are obtained by conversion from fastnlo format.

Which folder should these be added to?

cc @enocera

**Comment by scarlehoff** [comment]
What are these theory grids? Do they correspond to existing datasets? Are they completely new?

I'm putting the grids at NNLO that substitute previous NLO grids in theory 600.

**Comment by enocera** [comment]
These grids are for (part of) the old ttbar data and for jet data (old and new). I'd suggest to put them in theory 600, then.

**Comment by scarlehoff** [comment]
I would keep the names they already have in this repository since the individual names of the grids do not matter and there are already many theories that depend on those names.

**Comment by t7phy** [comment]
I don't mean to rename the ones that are already there, what I mean is that the new ones that I add, I will follow the same names as we agreed for the new buildmaster, the question is whether there should be - or _ before the BINX ? Is that what you mean, that it doesn't matter?

**Comment by scarlehoff** [comment]
The name of the grids are only used in the `theory` part of the new data implementation and they usually have either the name of the dataset + BINX

https://github.com/NNPDF/theories/blob/main/data/yamldb/400/ATLAS_DY_2D_8TEV_LOWMASS.yaml

but some times they even contain arxiv references
https://github.com/NNPDF/theories/blob/main/data/yamldb/400/ATLAS_WM_JET_8TEV_PT.yaml

tbh, it doesn't matter (to me) but if I have to choose, just follow whatever is close to the names that are already there.

**Comment by felixhekhorn** [comment]
> but some times they even contain arxiv references

Please avoid arXiv numbers, or to be more specific please avoid a dot `.` - this way we can split more easily by suffix

**Comment by scarlehoff** [comment]
@t7phy what is the status of this?

It would be good to have these in light of #11 since if the difference are small enough with respect to the ones we have it might nice to use them also for MHOU.

Are they converted from plougshare?

**Comment by t7phy** [comment]
> @t7phy what is the status of this?
> 
> It would be good to have these in light of #11 since if the difference are small enough with respect to the ones we have it might nice to use them also for MHOU.
> 
> Are they converted from plougshare?

They were all converted however I will have to reconvert them as previously the metadata was not copied from fastnlo grids, the feature was recently added in pineappl and since them I have been very caught up with some work. I can have them all ready next week. Shall I just push to the master in the 600 directory or will I need to open a PR?

**Comment by scarlehoff** [comment]
Open a PR please, so that we can also do some test and keep track of the dicussion.

**Comment by t7phy** [comment]
@scarlehoff  Some grid files are above the 100 MB threshold, how do I go about adding them? git lfs?

**Comment by scarlehoff** [comment]
Yes... I was hoping this wouldn't happen so soon (#1 is becoming a prioririty now...)

(just to make sure, you mean the grid and not the fktable? If you optimize the grid with pineappl does it go below 100 mb?)

**Comment by t7phy** [comment]
yes, the grid. I am not sure about optimizing, I just converted from fnlo to pineappl, however some of the files are ~200-250 mb so I doubt they could go below 100
